####
# ATENTION:
# Replace all occurences of easyvalue with your project's name
####

# v2 syntax
version: '3'

services:

  mysql:
    image: mysql:5.7
    container_name: tcc-mysql
    volumes:
      - ./storage/myslq:/var/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=tcc
      - MYSQL_DATABASE=tcc
      - MYSQL_USER=tcc
      - MYSQL_PASSWORD=tcc


  # PHP (with Caddy)
  app:
    image: ambientum/php:7.3-nginx
    container_name: tccapp
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80